defaultProject: strongsville-city-schools
defaultLocation: US
defaultDataset: dataform
defaultAssertionDataset: dataform_assertions
dataformCoreVersion: 3.0.0-beta.4
vars:
  do_full_refresh: "false"
  executionProject: "dev"
  raw: "llb-gcp-edp-raw-dev"
  work: "llb-gcp-edp-work-dev"
  obt: "llb-gcp-edp-obt-dev"