config {
  type: "incremental",
  database: "strongsville-city-schools",
  schema: "dssrpm_shop_floor_inspection",
  name: "emp_master2",
  uniqueKey: ["surrogate_key"],
  bigquery: {
    partitionBy: "eff_start_ts",
    clusterBy: ["employee_master_id"],
    /*updatePartitionFilter: "eff_start_ts = eff_start_ts or eff_start_ts is null"*/
  }
}

pre_operations {
  declare curr_ts timestamp default current_timestamp();
}

with 
-- current active dimension records
current_target as (
  select *
  from `strongsville-city-schools.dssrpm_shop_floor_inspection.emp_master`
  where eff_end_ts is null
),

-- new or changed rows (or marked deleted)
changed_or_new_records as (
  select
    s.employee_master_id,
    s.employee_name,
    s.employee_number,
    s.shift,
    s.is_active,
    s.loaded_from_file,
    s.is_deleted
  from `strongsville-city-schools.dssrpm_shop_floor_inspection.stg_emp_master` s
  left join current_target d
    on s.employee_master_id = d.employee_master_id
  where d.surrogate_key is null
    or s.is_deleted = 'Y'
    or (
      ifnull(s.employee_name,'') != ifnull(d.employee_name,'') OR
      ifnull(s.employee_number,-1) != ifnull(d.employee_number,-1) OR
      ifnull(s.shift,-1) != ifnull(d.shift,-1) OR
      ifnull(s.is_active,'') != ifnull(d.is_active,'') OR
      ifnull(s.loaded_from_file,'') != ifnull(d.loaded_from_file,'')
    )
),

-- inserted new versions (including deleted versions that don't exist in the target)
new_rows as (
  select
    generate_uuid() as surrogate_key,
    employee_master_id,
    employee_name,
    employee_number,
    shift,
    is_active,
    loaded_from_file,
    curr_ts as eff_start_ts,
    case when is_deleted = 'Y' then timestamp_sub(curr_ts, interval 1 second)
    end as eff_end_ts,
    is_deleted
  from changed_or_new_records
),

-- expire old versions
expired_rows as (
  select
    d.surrogate_key,
    d.employee_master_id,
    d.employee_name,
    d.employee_number,
    d.shift,
    d.is_active,
    d.loaded_from_file,
    d.eff_start_ts,
    timestamp_sub(curr_ts, interval 1 second) as eff_end_ts,
    d.is_deleted
  from current_target d inner join changed_or_new_records s
    on s.employee_master_id = d.employee_master_id
)

-- final incremental write
select * from new_rows
union all
select * from expired_rows
